spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  access:
    key:
      id: ${AWS_ACCESS_KEY_ID}
  secret:
    access:
      key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket:
      name: ${BUCKET_NAME}

gemini:
  api:
    key: ${GEMINI_API_KEY}
  model:
    name: ${GEMINI_MODEL_NAME}

admin:
  token:
    owner: ${OWNER_SECRET_CODE}
    manager: ${MANAGER_SECRET_CODE}
    master: ${MASTER_SECRET_CODE}

